# Generated by Django 4.2 on 2023-05-27 07:54

from django.db import migrations, models
import shopapp.models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0003_rename_name_category_title_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.category_image_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.product_image_directory_path,
            ),
        ),
    ]
