# Generated by Django 4.2 on 2023-06-06 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0007_cartitem_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="product_id",
            new_name="product",
        ),
    ]
