# Generated by Django 4.2 on 2023-06-08 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shopapp", "0008_rename_product_id_cartitem_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.IntegerField(blank=True, null=True)),
                ("delivery_type", models.CharField(max_length=128)),
                ("payment_type", models.CharField(max_length=128)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
                ),
                ("status", models.CharField(max_length=128)),
                ("city", models.CharField(max_length=128)),
                ("address", models.CharField(max_length=512)),
                ("products", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
